language: php

php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit
